// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  signalId: __t.u64().name("signal_id"),
  agentId: __t.u64().name("agent_id"),
  conditionId: __t.string().name("condition_id"),
  createdAt: __t.timestamp().name("created_at"),
  probYes: __t.f64().name("prob_yes"),
  expectedDelta: __t.f64().name("expected_delta"),
  halfLifeMin: __t.f64().name("half_life_min"),
  confidence: __t.f64(),
  rationale: __t.string(),
  latencyMs: __t.u32().name("latency_ms"),
  brier: __t.option(__t.f64()),
  reactionErr: __t.option(__t.f64()).name("reaction_err"),
});
