// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  generation: __t.u32(),
  parentId: __t.u64().name("parent_id"),
  status: __t.string(),
  tier: __t.string(),
  niche: __t.string(),
  persona: __t.string(),
  instructions: __t.string(),
  temperature: __t.f64(),
  styleTags: __t.array(__t.string()).name("style_tags"),
  weight: __t.f64(),
  nScored: __t.u32().name("n_scored"),
  brier: __t.f64(),
  logLoss: __t.f64().name("log_loss"),
  reactionMae: __t.f64().name("reaction_mae"),
  directionHit: __t.f64().name("direction_hit"),
  lineageNote: __t.string().name("lineage_note"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
