// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  dedupeKey: __t.string().name("dedupe_key"),
  kind: __t.string(),
  sessionId: __t.u64().name("session_id"),
  status: __t.string(),
  priority: __t.i32(),
  deps: __t.array(__t.u64()),
  payload: __t.string(),
  result: __t.string(),
  error: __t.string(),
  attempts: __t.u32(),
  maxAttempts: __t.u32().name("max_attempts"),
  leaseOwner: __t.string().name("lease_owner"),
  leaseUntil: __t.timestamp().name("lease_until"),
  notBefore: __t.timestamp().name("not_before"),
  model: __t.string(),
  tokensIn: __t.u32().name("tokens_in"),
  tokensOut: __t.u32().name("tokens_out"),
  cachedTokens: __t.u32().name("cached_tokens"),
  costUsd: __t.f64().name("cost_usd"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
