// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  component: __t.string().primaryKey(),
  a: __t.f64(),
  b: __t.f64(),
  n: __t.u32(),
  eceBefore: __t.f64().name("ece_before"),
  eceAfter: __t.f64().name("ece_after"),
  brierBefore: __t.f64().name("brier_before"),
  brierAfter: __t.f64().name("brier_after"),
  updatedAt: __t.timestamp().name("updated_at"),
});
