// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  RiskConfig,
  IntelConfig,
  SessionMarketInput,
  SeedFileInput,
} from "./types";

export default {
  name: __t.string(),
  mode: __t.string(),
  bankrollUsd: __t.f64(),
  get risk() {
    return RiskConfig;
  },
  get intel() {
    return IntelConfig;
  },
  thesis: __t.string(),
  get markets() {
    return __t.array(SessionMarketInput);
  },
  get files() {
    return __t.array(SeedFileInput);
  },
};
