// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  ref: __t.string(),
  sessionId: __t.u64().name("session_id"),
  conditionId: __t.string().name("condition_id"),
  signalRef: __t.string().name("signal_ref"),
  createdAt: __t.timestamp().name("created_at"),
  action: __t.string(),
  strategy: __t.string(),
  fairProb: __t.f64().name("fair_prob"),
  marketPrice: __t.f64().name("market_price"),
  edge: __t.f64(),
  kellyFraction: __t.f64().name("kelly_fraction"),
  sizeUsd: __t.f64().name("size_usd"),
  confirmations: __t.u32(),
  confidence: __t.f64(),
  verdict: __t.string(),
  reasons: __t.array(__t.string()),
});
