// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  workerId: __t.string().primaryKey().name("worker_id"),
  identity: __t.identity(),
  lastSeen: __t.timestamp().name("last_seen"),
  version: __t.string(),
  status: __t.string(),
  inflight: __t.u32(),
  info: __t.string(),
});
