// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  subject: __t.string(),
  agentId: __t.u64().name("agent_id"),
  parentId: __t.u64().name("parent_id"),
  generation: __t.u32(),
  baselineScore: __t.f64().name("baseline_score"),
  candidateScore: __t.f64().name("candidate_score"),
  nEval: __t.u32().name("n_eval"),
  decision: __t.string(),
  mutation: __t.string(),
  metric: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
