// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.1 (commit 3d7607082ab47257adeb7c25164536511237f2b5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddCalibrationSamplesReducer from "./add_calibration_samples_reducer";
import AddSessionMarketReducer from "./add_session_market_reducer";
import ApproveLiveReducer from "./approve_live_reducer";
import BookFillReducer from "./book_fill_reducer";
import CancelTasksReducer from "./cancel_tasks_reducer";
import ClaimOperatorReducer from "./claim_operator_reducer";
import ClaimTasksReducer from "./claim_tasks_reducer";
import CompleteTaskReducer from "./complete_task_reducer";
import CreateSessionReducer from "./create_session_reducer";
import DeleteSeedFileReducer from "./delete_seed_file_reducer";
import EnqueueTasksReducer from "./enqueue_tasks_reducer";
import ExtendLeasesReducer from "./extend_leases_reducer";
import FailTaskReducer from "./fail_task_reducer";
import HeartbeatReducer from "./heartbeat_reducer";
import InsertNewsReducer from "./insert_news_reducer";
import InsertPathForecastReducer from "./insert_path_forecast_reducer";
import InsertPriceBarsReducer from "./insert_price_bars_reducer";
import InsertSignalReducer from "./insert_signal_reducer";
import InvalidateMemEdgesReducer from "./invalidate_mem_edges_reducer";
import LogActivitiesReducer from "./log_activities_reducer";
import MarkToMarketReducer from "./mark_to_market_reducer";
import MergeMemNodesReducer from "./merge_mem_nodes_reducer";
import RecordDecisionReducer from "./record_decision_reducer";
import RecordEquityReducer from "./record_equity_reducer";
import RecordLlmUsageReducer from "./record_llm_usage_reducer";
import RecordReflexStatsReducer from "./record_reflex_stats_reducer";
import RecordTrialReducer from "./record_trial_reducer";
import RemoveSessionMarketReducer from "./remove_session_market_reducer";
import ResolveCalibrationSamplesReducer from "./resolve_calibration_samples_reducer";
import ResolveOperatorRequestReducer from "./resolve_operator_request_reducer";
import ScoreAgentForecastsReducer from "./score_agent_forecasts_reducer";
import ScoreSignalsReducer from "./score_signals_reducer";
import SetFlagReducer from "./set_flag_reducer";
import SetMarketResolutionReducer from "./set_market_resolution_reducer";
import SetReflexEnabledReducer from "./set_reflex_enabled_reducer";
import SetSessionModeReducer from "./set_session_mode_reducer";
import SetSessionStatusReducer from "./set_session_status_reducer";
import UnmergeMemNodeReducer from "./unmerge_mem_node_reducer";
import UpdateNewsTriageReducer from "./update_news_triage_reducer";
import UpdateSessionConfigReducer from "./update_session_config_reducer";
import UpsertAgentsReducer from "./upsert_agents_reducer";
import UpsertCalibratorReducer from "./upsert_calibrator_reducer";
import UpsertMarketsReducer from "./upsert_markets_reducer";
import UpsertMemEdgesReducer from "./upsert_mem_edges_reducer";
import UpsertMemNodesReducer from "./upsert_mem_nodes_reducer";
import UpsertOrdersReducer from "./upsert_orders_reducer";
import UpsertReflexesReducer from "./upsert_reflexes_reducer";
import UpsertSeedFileReducer from "./upsert_seed_file_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ActivityRow from "./activity_table";
import AgentRow from "./agent_table";
import AgentForecastRow from "./agent_forecast_table";
import AgentTaskRow from "./agent_task_table";
import CalibrationSampleRow from "./calibration_sample_table";
import CalibratorRow from "./calibrator_table";
import DecisionRow from "./decision_table";
import EngineHeartbeatRow from "./engine_heartbeat_table";
import EquityPointRow from "./equity_point_table";
import EvolutionTrialRow from "./evolution_trial_table";
import GlobalFlagRow from "./global_flag_table";
import LlmUsageRow from "./llm_usage_table";
import MarketRow from "./market_table";
import MemEdgeRow from "./mem_edge_table";
import MemNodeRow from "./mem_node_table";
import NewsItemRow from "./news_item_table";
import OperatorRow from "./operator_table";
import OperatorRequestRow from "./operator_request_table";
import PathForecastRow from "./path_forecast_table";
import PositionRow from "./position_table";
import PriceBarRow from "./price_bar_table";
import ReflexRow from "./reflex_table";
import SeedFileRow from "./seed_file_table";
import SessionRow from "./session_table";
import SessionMarketRow from "./session_market_table";
import SignalRow from "./signal_table";
import TradeOrderRow from "./trade_order_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  activity: __table({
    name: 'activity',
    indexes: [
      { accessor: 'id', name: 'activity_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sessionId', name: 'activity_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'activity_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActivityRow),
  agent: __table({
    name: 'agent',
    indexes: [
      { accessor: 'id', name: 'agent_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'status', name: 'agent_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'agent_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AgentRow),
  agentForecast: __table({
    name: 'agent_forecast',
    indexes: [
      { accessor: 'agentId', name: 'agent_forecast_agent_id_idx_btree', algorithm: 'btree', columns: [
        'agentId',
      ] },
      { accessor: 'id', name: 'agent_forecast_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'signalId', name: 'agent_forecast_signal_id_idx_btree', algorithm: 'btree', columns: [
        'signalId',
      ] },
    ],
    constraints: [
      { name: 'agent_forecast_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AgentForecastRow),
  agentTask: __table({
    name: 'agent_task',
    indexes: [
      { accessor: 'dedupeKey', name: 'agent_task_dedupe_key_idx_btree', algorithm: 'btree', columns: [
        'dedupeKey',
      ] },
      { accessor: 'id', name: 'agent_task_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'status', name: 'agent_task_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'agent_task_dedupe_key_key', constraint: 'unique', columns: ['dedupeKey'] },
      { name: 'agent_task_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AgentTaskRow),
  calibrationSample: __table({
    name: 'calibration_sample',
    indexes: [
      { accessor: 'component', name: 'calibration_sample_component_idx_btree', algorithm: 'btree', columns: [
        'component',
      ] },
      { accessor: 'id', name: 'calibration_sample_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'calibration_sample_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CalibrationSampleRow),
  calibrator: __table({
    name: 'calibrator',
    indexes: [
      { accessor: 'component', name: 'calibrator_component_idx_btree', algorithm: 'btree', columns: [
        'component',
      ] },
    ],
    constraints: [
      { name: 'calibrator_component_key', constraint: 'unique', columns: ['component'] },
    ],
  }, CalibratorRow),
  decision: __table({
    name: 'decision',
    indexes: [
      { accessor: 'id', name: 'decision_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'ref', name: 'decision_ref_idx_btree', algorithm: 'btree', columns: [
        'ref',
      ] },
      { accessor: 'sessionId', name: 'decision_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'decision_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'decision_ref_key', constraint: 'unique', columns: ['ref'] },
    ],
  }, DecisionRow),
  engineHeartbeat: __table({
    name: 'engine_heartbeat',
    indexes: [
      { accessor: 'workerId', name: 'engine_heartbeat_worker_id_idx_btree', algorithm: 'btree', columns: [
        'workerId',
      ] },
    ],
    constraints: [
      { name: 'engine_heartbeat_worker_id_key', constraint: 'unique', columns: ['workerId'] },
    ],
  }, EngineHeartbeatRow),
  equityPoint: __table({
    name: 'equity_point',
    indexes: [
      { accessor: 'id', name: 'equity_point_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sessionId', name: 'equity_point_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'equity_point_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EquityPointRow),
  evolutionTrial: __table({
    name: 'evolution_trial',
    indexes: [
      { accessor: 'id', name: 'evolution_trial_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'evolution_trial_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EvolutionTrialRow),
  globalFlag: __table({
    name: 'global_flag',
    indexes: [
      { accessor: 'key', name: 'global_flag_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'global_flag_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, GlobalFlagRow),
  llmUsage: __table({
    name: 'llm_usage',
    indexes: [
      { accessor: 'key', name: 'llm_usage_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'llm_usage_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, LlmUsageRow),
  market: __table({
    name: 'market',
    indexes: [
      { accessor: 'conditionId', name: 'market_condition_id_idx_btree', algorithm: 'btree', columns: [
        'conditionId',
      ] },
    ],
    constraints: [
      { name: 'market_condition_id_key', constraint: 'unique', columns: ['conditionId'] },
    ],
  }, MarketRow),
  memEdge: __table({
    name: 'mem_edge',
    indexes: [
      { accessor: 'dst', name: 'mem_edge_dst_idx_btree', algorithm: 'btree', columns: [
        'dst',
      ] },
      { accessor: 'id', name: 'mem_edge_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'key', name: 'mem_edge_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
      { accessor: 'src', name: 'mem_edge_src_idx_btree', algorithm: 'btree', columns: [
        'src',
      ] },
    ],
    constraints: [
      { name: 'mem_edge_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'mem_edge_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, MemEdgeRow),
  memNode: __table({
    name: 'mem_node',
    indexes: [
      { accessor: 'id', name: 'mem_node_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'key', name: 'mem_node_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
      { accessor: 'kind', name: 'mem_node_kind_idx_btree', algorithm: 'btree', columns: [
        'kind',
      ] },
    ],
    constraints: [
      { name: 'mem_node_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'mem_node_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, MemNodeRow),
  newsItem: __table({
    name: 'news_item',
    indexes: [
      { accessor: 'hash', name: 'news_item_hash_idx_btree', algorithm: 'btree', columns: [
        'hash',
      ] },
      { accessor: 'id', name: 'news_item_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'status', name: 'news_item_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'news_item_hash_key', constraint: 'unique', columns: ['hash'] },
      { name: 'news_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NewsItemRow),
  operator: __table({
    name: 'operator',
    indexes: [
      { accessor: 'identity', name: 'operator_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'operator_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, OperatorRow),
  operatorRequest: __table({
    name: 'operator_request',
    indexes: [
      { accessor: 'id', name: 'operator_request_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'operator_request_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OperatorRequestRow),
  pathForecast: __table({
    name: 'path_forecast',
    indexes: [
      { accessor: 'conditionId', name: 'path_forecast_condition_id_idx_btree', algorithm: 'btree', columns: [
        'conditionId',
      ] },
      { accessor: 'id', name: 'path_forecast_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'path_forecast_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PathForecastRow),
  position: __table({
    name: 'position',
    indexes: [
      { accessor: 'id', name: 'position_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sessionId', name: 'position_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'position_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PositionRow),
  priceBar: __table({
    name: 'price_bar',
    indexes: [
      { accessor: 'conditionId', name: 'price_bar_condition_id_idx_btree', algorithm: 'btree', columns: [
        'conditionId',
      ] },
      { accessor: 'id', name: 'price_bar_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'price_bar_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PriceBarRow),
  reflex: __table({
    name: 'reflex',
    indexes: [
      { accessor: 'key', name: 'reflex_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'reflex_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, ReflexRow),
  seedFile: __table({
    name: 'seed_file',
    indexes: [
      { accessor: 'id', name: 'seed_file_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sessionId', name: 'seed_file_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'seed_file_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SeedFileRow),
  session: __table({
    name: 'session',
    indexes: [
      { accessor: 'id', name: 'session_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'owner', name: 'session_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
    ],
    constraints: [
      { name: 'session_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SessionRow),
  sessionMarket: __table({
    name: 'session_market',
    indexes: [
      { accessor: 'conditionId', name: 'session_market_condition_id_idx_btree', algorithm: 'btree', columns: [
        'conditionId',
      ] },
      { accessor: 'id', name: 'session_market_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sessionId', name: 'session_market_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'session_market_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SessionMarketRow),
  signal: __table({
    name: 'signal',
    indexes: [
      { accessor: 'conditionId', name: 'signal_condition_id_idx_btree', algorithm: 'btree', columns: [
        'conditionId',
      ] },
      { accessor: 'id', name: 'signal_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'newsId', name: 'signal_news_id_idx_btree', algorithm: 'btree', columns: [
        'newsId',
      ] },
      { accessor: 'ref', name: 'signal_ref_idx_btree', algorithm: 'btree', columns: [
        'ref',
      ] },
    ],
    constraints: [
      { name: 'signal_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'signal_ref_key', constraint: 'unique', columns: ['ref'] },
    ],
  }, SignalRow),
  tradeOrder: __table({
    name: 'trade_order',
    indexes: [
      { accessor: 'id', name: 'trade_order_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'ref', name: 'trade_order_ref_idx_btree', algorithm: 'btree', columns: [
        'ref',
      ] },
      { accessor: 'sessionId', name: 'trade_order_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'trade_order_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'trade_order_ref_key', constraint: 'unique', columns: ['ref'] },
    ],
  }, TradeOrderRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_calibration_samples", AddCalibrationSamplesReducer),
  __reducerSchema("add_session_market", AddSessionMarketReducer),
  __reducerSchema("approve_live", ApproveLiveReducer),
  __reducerSchema("book_fill", BookFillReducer),
  __reducerSchema("cancel_tasks", CancelTasksReducer),
  __reducerSchema("claim_operator", ClaimOperatorReducer),
  __reducerSchema("claim_tasks", ClaimTasksReducer),
  __reducerSchema("complete_task", CompleteTaskReducer),
  __reducerSchema("create_session", CreateSessionReducer),
  __reducerSchema("delete_seed_file", DeleteSeedFileReducer),
  __reducerSchema("enqueue_tasks", EnqueueTasksReducer),
  __reducerSchema("extend_leases", ExtendLeasesReducer),
  __reducerSchema("fail_task", FailTaskReducer),
  __reducerSchema("heartbeat", HeartbeatReducer),
  __reducerSchema("insert_news", InsertNewsReducer),
  __reducerSchema("insert_path_forecast", InsertPathForecastReducer),
  __reducerSchema("insert_price_bars", InsertPriceBarsReducer),
  __reducerSchema("insert_signal", InsertSignalReducer),
  __reducerSchema("invalidate_mem_edges", InvalidateMemEdgesReducer),
  __reducerSchema("log_activities", LogActivitiesReducer),
  __reducerSchema("mark_to_market", MarkToMarketReducer),
  __reducerSchema("merge_mem_nodes", MergeMemNodesReducer),
  __reducerSchema("record_decision", RecordDecisionReducer),
  __reducerSchema("record_equity", RecordEquityReducer),
  __reducerSchema("record_llm_usage", RecordLlmUsageReducer),
  __reducerSchema("record_reflex_stats", RecordReflexStatsReducer),
  __reducerSchema("record_trial", RecordTrialReducer),
  __reducerSchema("remove_session_market", RemoveSessionMarketReducer),
  __reducerSchema("resolve_calibration_samples", ResolveCalibrationSamplesReducer),
  __reducerSchema("resolve_operator_request", ResolveOperatorRequestReducer),
  __reducerSchema("score_agent_forecasts", ScoreAgentForecastsReducer),
  __reducerSchema("score_signals", ScoreSignalsReducer),
  __reducerSchema("set_flag", SetFlagReducer),
  __reducerSchema("set_market_resolution", SetMarketResolutionReducer),
  __reducerSchema("set_reflex_enabled", SetReflexEnabledReducer),
  __reducerSchema("set_session_mode", SetSessionModeReducer),
  __reducerSchema("set_session_status", SetSessionStatusReducer),
  __reducerSchema("unmerge_mem_node", UnmergeMemNodeReducer),
  __reducerSchema("update_news_triage", UpdateNewsTriageReducer),
  __reducerSchema("update_session_config", UpdateSessionConfigReducer),
  __reducerSchema("upsert_agents", UpsertAgentsReducer),
  __reducerSchema("upsert_calibrator", UpsertCalibratorReducer),
  __reducerSchema("upsert_markets", UpsertMarketsReducer),
  __reducerSchema("upsert_mem_edges", UpsertMemEdgesReducer),
  __reducerSchema("upsert_mem_nodes", UpsertMemNodesReducer),
  __reducerSchema("upsert_orders", UpsertOrdersReducer),
  __reducerSchema("upsert_reflexes", UpsertReflexesReducer),
  __reducerSchema("upsert_seed_file", UpsertSeedFileReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

