// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  hour: __t.timestamp(),
  route: __t.string(),
  model: __t.string(),
  calls: __t.u32(),
  tokensIn: __t.f64().name("tokens_in"),
  tokensOut: __t.f64().name("tokens_out"),
  cachedTokens: __t.f64().name("cached_tokens"),
  thoughtTokens: __t.f64().name("thought_tokens"),
  costUsd: __t.f64().name("cost_usd"),
});
