// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  conditionId: __t.string().primaryKey().name("condition_id"),
  marketId: __t.string().name("market_id"),
  question: __t.string(),
  slug: __t.string(),
  description: __t.string(),
  category: __t.string(),
  endDate: __t.string().name("end_date"),
  yesTokenId: __t.string().name("yes_token_id"),
  noTokenId: __t.string().name("no_token_id"),
  tickSize: __t.f64().name("tick_size"),
  minOrderSize: __t.f64().name("min_order_size"),
  negRisk: __t.bool().name("neg_risk"),
  eventId: __t.string().name("event_id"),
  negRiskMarketId: __t.string().name("neg_risk_market_id"),
  outcomeLabel: __t.string().name("outcome_label"),
  feeRate: __t.f64().name("fee_rate"),
  active: __t.bool(),
  closed: __t.bool(),
  resolved: __t.bool(),
  outcomeYes: __t.option(__t.f64()).name("outcome_yes"),
  bestBid: __t.f64().name("best_bid"),
  bestAsk: __t.f64().name("best_ask"),
  lastPrice: __t.f64().name("last_price"),
  volumeDay: __t.f64().name("volume_day"),
  liquidity: __t.f64(),
  updatedAt: __t.timestamp().name("updated_at"),
});
