// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  key: __t.string(),
  src: __t.u64(),
  dst: __t.u64(),
  rel: __t.string(),
  weight: __t.f64(),
  value: __t.f64(),
  lagMin: __t.f64().name("lag_min"),
  evidence: __t.string(),
  sessionId: __t.u64().name("session_id"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  validFrom: __t.timestamp().name("valid_from"),
  invalidatedAt: __t.option(__t.timestamp()).name("invalidated_at"),
});
