// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  key: __t.string(),
  kind: __t.string(),
  label: __t.string(),
  aliases: __t.array(__t.string()),
  summary: __t.string(),
  sessionId: __t.u64().name("session_id"),
  status: __t.string(),
  salience: __t.f64(),
  mentionCount: __t.u32().name("mention_count"),
  helpful: __t.u32(),
  harmful: __t.u32(),
  embedding: __t.array(__t.f32()),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
