// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  hash: __t.string(),
  source: __t.string(),
  feed: __t.string(),
  title: __t.string(),
  summary: __t.string(),
  url: __t.string(),
  publishedAt: __t.timestamp().name("published_at"),
  ingestedAt: __t.timestamp().name("ingested_at"),
  status: __t.string(),
  urgency: __t.f64(),
  sentiment: __t.f64(),
  novelty: __t.f64(),
  eventType: __t.string().name("event_type"),
  entities: __t.array(__t.string()),
  marketIds: __t.array(__t.string()).name("market_ids"),
  triageNote: __t.string().name("triage_note"),
});
