// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  conditionId: __t.string().name("condition_id"),
  createdAt: __t.timestamp().name("created_at"),
  baseTs: __t.timestamp().name("base_ts"),
  stepSec: __t.u32().name("step_sec"),
  lastPrice: __t.f64().name("last_price"),
  point: __t.array(__t.f64()),
  q10: __t.array(__t.f64()).name("q_10"),
  q90: __t.array(__t.f64()).name("q_90"),
  model: __t.string(),
  newsAdjusted: __t.bool().name("news_adjusted"),
});
