// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  conditionId: __t.string().name("condition_id"),
  outcome: __t.string(),
  shares: __t.f64(),
  avgPrice: __t.f64().name("avg_price"),
  costUsd: __t.f64().name("cost_usd"),
  markPrice: __t.f64().name("mark_price"),
  unrealizedPnlUsd: __t.f64().name("unrealized_pnl_usd"),
  realizedPnlUsd: __t.f64().name("realized_pnl_usd"),
  closed: __t.bool(),
  strategy: __t.string(),
  targetPrice: __t.f64().name("target_price"),
  stopPrice: __t.f64().name("stop_price"),
  timeStopMicros: __t.i64().name("time_stop_micros"),
  openedAt: __t.timestamp().name("opened_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
