// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  conditionId: __t.string().name("condition_id"),
  ts: __t.timestamp(),
  open: __t.f64(),
  high: __t.f64(),
  low: __t.f64(),
  close: __t.f64(),
  bid: __t.f64(),
  ask: __t.f64(),
});
