// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  qtype: __t.string(),
  instructions: __t.string(),
  criteriaKeys: __t.array(__t.string()).name("criteria_keys"),
  criteriaText: __t.array(__t.string()).name("criteria_text"),
  threshold: __t.f64(),
  provider: __t.string(),
  version: __t.u32(),
  candidateInstructions: __t.string().name("candidate_instructions"),
  candidateThreshold: __t.f64().name("candidate_threshold"),
  nFired: __t.u32().name("n_fired"),
  nResolved: __t.u32().name("n_resolved"),
  brier: __t.f64(),
  hitRate: __t.f64().name("hit_rate"),
  avgLatencyMs: __t.f64().name("avg_latency_ms"),
  enabled: __t.bool(),
  coachNote: __t.string().name("coach_note"),
  updatedAt: __t.timestamp().name("updated_at"),
});
