// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  RiskConfig,
  IntelConfig,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  name: __t.string(),
  slug: __t.string(),
  status: __t.string(),
  statusReason: __t.string().name("status_reason"),
  mode: __t.string(),
  liveApproved: __t.bool().name("live_approved"),
  bankrollUsd: __t.f64().name("bankroll_usd"),
  cashUsd: __t.f64().name("cash_usd"),
  equityUsd: __t.f64().name("equity_usd"),
  peakEquityUsd: __t.f64().name("peak_equity_usd"),
  dayStartEquityUsd: __t.f64().name("day_start_equity_usd"),
  realizedPnlUsd: __t.f64().name("realized_pnl_usd"),
  feesPaidUsd: __t.f64().name("fees_paid_usd"),
  exposureUsd: __t.f64().name("exposure_usd"),
  get risk() {
    return RiskConfig;
  },
  get intel() {
    return IntelConfig;
  },
  thesis: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
