// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  ref: __t.string(),
  newsId: __t.u64().name("news_id"),
  conditionId: __t.string().name("condition_id"),
  createdAt: __t.timestamp().name("created_at"),
  layer: __t.string(),
  expectedDelta: __t.f64().name("expected_delta"),
  deltaQ10: __t.f64().name("delta_q_10"),
  deltaQ90: __t.f64().name("delta_q_90"),
  halfLifeMin: __t.f64().name("half_life_min"),
  probYes: __t.f64().name("prob_yes"),
  probMarket: __t.f64().name("prob_market"),
  confidence: __t.f64(),
  disagreement: __t.f64(),
  nAgents: __t.u32().name("n_agents"),
  rationale: __t.string(),
  analogCount: __t.u32().name("analog_count"),
  analogMeanDelta: __t.f64().name("analog_mean_delta"),
  realizedShort: __t.option(__t.f64()).name("realized_short"),
  realizedMid: __t.option(__t.f64()).name("realized_mid"),
  realizedLong: __t.option(__t.f64()).name("realized_long"),
  absError: __t.option(__t.f64()).name("abs_error"),
  status: __t.string(),
});
