// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  ref: __t.string(),
  sessionId: __t.u64().name("session_id"),
  decisionRef: __t.string().name("decision_ref"),
  conditionId: __t.string().name("condition_id"),
  tokenId: __t.string().name("token_id"),
  outcome: __t.string(),
  side: __t.string(),
  price: __t.f64(),
  size: __t.f64(),
  status: __t.string(),
  mode: __t.string(),
  externalId: __t.string().name("external_id"),
  filledSize: __t.f64().name("filled_size"),
  avgFillPrice: __t.f64().name("avg_fill_price"),
  feeUsd: __t.f64().name("fee_usd"),
  note: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
