// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Activity = __t.object("Activity", {
  id: __t.u64(),
  sessionId: __t.u64(),
  ts: __t.timestamp(),
  level: __t.string(),
  kind: __t.string(),
  message: __t.string(),
  refId: __t.string(),
});
export type Activity = __Infer<typeof Activity>;

export const ActivityInput = __t.object("ActivityInput", {
  sessionId: __t.u64(),
  level: __t.string(),
  kind: __t.string(),
  message: __t.string(),
  refId: __t.string(),
});
export type ActivityInput = __Infer<typeof ActivityInput>;

export const Agent = __t.object("Agent", {
  id: __t.u64(),
  name: __t.string(),
  generation: __t.u32(),
  parentId: __t.u64(),
  status: __t.string(),
  tier: __t.string(),
  niche: __t.string(),
  persona: __t.string(),
  instructions: __t.string(),
  temperature: __t.f64(),
  styleTags: __t.array(__t.string()),
  weight: __t.f64(),
  nScored: __t.u32(),
  brier: __t.f64(),
  logLoss: __t.f64(),
  reactionMae: __t.f64(),
  directionHit: __t.f64(),
  lineageNote: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Agent = __Infer<typeof Agent>;

export const AgentForecast = __t.object("AgentForecast", {
  id: __t.u64(),
  signalId: __t.u64(),
  agentId: __t.u64(),
  conditionId: __t.string(),
  createdAt: __t.timestamp(),
  probYes: __t.f64(),
  expectedDelta: __t.f64(),
  halfLifeMin: __t.f64(),
  confidence: __t.f64(),
  rationale: __t.string(),
  latencyMs: __t.u32(),
  brier: __t.option(__t.f64()),
  reactionErr: __t.option(__t.f64()),
});
export type AgentForecast = __Infer<typeof AgentForecast>;

export const AgentForecastInput = __t.object("AgentForecastInput", {
  agentId: __t.u64(),
  probYes: __t.f64(),
  expectedDelta: __t.f64(),
  halfLifeMin: __t.f64(),
  confidence: __t.f64(),
  rationale: __t.string(),
  latencyMs: __t.u32(),
});
export type AgentForecastInput = __Infer<typeof AgentForecastInput>;

export const AgentForecastScoreInput = __t.object("AgentForecastScoreInput", {
  forecastId: __t.u64(),
  brier: __t.option(__t.f64()),
  reactionErr: __t.option(__t.f64()),
});
export type AgentForecastScoreInput = __Infer<typeof AgentForecastScoreInput>;

export const AgentInput = __t.object("AgentInput", {
  id: __t.u64(),
  name: __t.string(),
  generation: __t.u32(),
  parentId: __t.u64(),
  status: __t.string(),
  tier: __t.string(),
  niche: __t.string(),
  persona: __t.string(),
  instructions: __t.string(),
  temperature: __t.f64(),
  styleTags: __t.array(__t.string()),
  weight: __t.f64(),
  nScored: __t.u32(),
  brier: __t.f64(),
  logLoss: __t.f64(),
  reactionMae: __t.f64(),
  directionHit: __t.f64(),
  lineageNote: __t.string(),
});
export type AgentInput = __Infer<typeof AgentInput>;

export const AgentTask = __t.object("AgentTask", {
  id: __t.u64(),
  dedupeKey: __t.string(),
  kind: __t.string(),
  sessionId: __t.u64(),
  status: __t.string(),
  priority: __t.i32(),
  deps: __t.array(__t.u64()),
  payload: __t.string(),
  result: __t.string(),
  error: __t.string(),
  attempts: __t.u32(),
  maxAttempts: __t.u32(),
  leaseOwner: __t.string(),
  leaseUntil: __t.timestamp(),
  notBefore: __t.timestamp(),
  model: __t.string(),
  tokensIn: __t.u32(),
  tokensOut: __t.u32(),
  cachedTokens: __t.u32(),
  costUsd: __t.f64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AgentTask = __Infer<typeof AgentTask>;

export const CalibrationOutcomeInput = __t.object("CalibrationOutcomeInput", {
  sampleId: __t.u64(),
  outcome: __t.f64(),
});
export type CalibrationOutcomeInput = __Infer<typeof CalibrationOutcomeInput>;

export const CalibrationSample = __t.object("CalibrationSample", {
  id: __t.u64(),
  component: __t.string(),
  version: __t.u32(),
  refId: __t.string(),
  prob: __t.f64(),
  answer: __t.string(),
  state: __t.string(),
  outcome: __t.option(__t.f64()),
  createdAt: __t.timestamp(),
  resolvedAt: __t.option(__t.timestamp()),
});
export type CalibrationSample = __Infer<typeof CalibrationSample>;

export const CalibrationSampleInput = __t.object("CalibrationSampleInput", {
  component: __t.string(),
  version: __t.u32(),
  refId: __t.string(),
  prob: __t.f64(),
  answer: __t.string(),
  state: __t.string(),
  outcome: __t.option(__t.f64()),
});
export type CalibrationSampleInput = __Infer<typeof CalibrationSampleInput>;

export const Calibrator = __t.object("Calibrator", {
  component: __t.string(),
  a: __t.f64(),
  b: __t.f64(),
  n: __t.u32(),
  eceBefore: __t.f64(),
  eceAfter: __t.f64(),
  brierBefore: __t.f64(),
  brierAfter: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type Calibrator = __Infer<typeof Calibrator>;

export const CalibratorInput = __t.object("CalibratorInput", {
  component: __t.string(),
  a: __t.f64(),
  b: __t.f64(),
  n: __t.u32(),
  eceBefore: __t.f64(),
  eceAfter: __t.f64(),
  brierBefore: __t.f64(),
  brierAfter: __t.f64(),
});
export type CalibratorInput = __Infer<typeof CalibratorInput>;

export const Decision = __t.object("Decision", {
  id: __t.u64(),
  ref: __t.string(),
  sessionId: __t.u64(),
  conditionId: __t.string(),
  signalRef: __t.string(),
  createdAt: __t.timestamp(),
  action: __t.string(),
  strategy: __t.string(),
  fairProb: __t.f64(),
  marketPrice: __t.f64(),
  edge: __t.f64(),
  kellyFraction: __t.f64(),
  sizeUsd: __t.f64(),
  confirmations: __t.u32(),
  confidence: __t.f64(),
  verdict: __t.string(),
  reasons: __t.array(__t.string()),
});
export type Decision = __Infer<typeof Decision>;

export const DecisionInput = __t.object("DecisionInput", {
  ref: __t.string(),
  sessionId: __t.u64(),
  conditionId: __t.string(),
  signalRef: __t.string(),
  action: __t.string(),
  strategy: __t.string(),
  fairProb: __t.f64(),
  marketPrice: __t.f64(),
  edge: __t.f64(),
  kellyFraction: __t.f64(),
  sizeUsd: __t.f64(),
  confirmations: __t.u32(),
  confidence: __t.f64(),
  verdict: __t.string(),
  reasons: __t.array(__t.string()),
});
export type DecisionInput = __Infer<typeof DecisionInput>;

export const EngineHeartbeat = __t.object("EngineHeartbeat", {
  workerId: __t.string(),
  identity: __t.identity(),
  lastSeen: __t.timestamp(),
  version: __t.string(),
  status: __t.string(),
  inflight: __t.u32(),
  info: __t.string(),
});
export type EngineHeartbeat = __Infer<typeof EngineHeartbeat>;

export const EquityPoint = __t.object("EquityPoint", {
  id: __t.u64(),
  sessionId: __t.u64(),
  ts: __t.timestamp(),
  equityUsd: __t.f64(),
  cashUsd: __t.f64(),
  exposureUsd: __t.f64(),
});
export type EquityPoint = __Infer<typeof EquityPoint>;

export const EquityPointInput = __t.object("EquityPointInput", {
  sessionId: __t.u64(),
  equityUsd: __t.f64(),
  cashUsd: __t.f64(),
  exposureUsd: __t.f64(),
});
export type EquityPointInput = __Infer<typeof EquityPointInput>;

export const EvolutionTrial = __t.object("EvolutionTrial", {
  id: __t.u64(),
  subject: __t.string(),
  agentId: __t.u64(),
  parentId: __t.u64(),
  generation: __t.u32(),
  baselineScore: __t.f64(),
  candidateScore: __t.f64(),
  nEval: __t.u32(),
  decision: __t.string(),
  mutation: __t.string(),
  metric: __t.string(),
  createdAt: __t.timestamp(),
});
export type EvolutionTrial = __Infer<typeof EvolutionTrial>;

export const FillInput = __t.object("FillInput", {
  sessionId: __t.u64(),
  conditionId: __t.string(),
  outcome: __t.string(),
  side: __t.string(),
  shares: __t.f64(),
  price: __t.f64(),
  fee: __t.f64(),
  strategy: __t.string(),
  targetPrice: __t.f64(),
  stopPrice: __t.f64(),
  timeStopMicros: __t.i64(),
});
export type FillInput = __Infer<typeof FillInput>;

export const GlobalFlag = __t.object("GlobalFlag", {
  key: __t.string(),
  value: __t.string(),
  updatedAt: __t.timestamp(),
});
export type GlobalFlag = __Infer<typeof GlobalFlag>;

export const HousekeepingTimer = __t.object("HousekeepingTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  job: __t.string(),
});
export type HousekeepingTimer = __Infer<typeof HousekeepingTimer>;

export const IntelConfig = __t.object("IntelConfig", {
  swarmSize: __t.u32(),
  proCallsPerHour: __t.u32(),
  escalateEdge: __t.f64(),
  escalateDisagreement: __t.f64(),
  dailyLlmBudgetUsd: __t.f64(),
});
export type IntelConfig = __Infer<typeof IntelConfig>;

export const LlmUsage = __t.object("LlmUsage", {
  key: __t.string(),
  hour: __t.timestamp(),
  route: __t.string(),
  model: __t.string(),
  calls: __t.u32(),
  tokensIn: __t.f64(),
  tokensOut: __t.f64(),
  cachedTokens: __t.f64(),
  thoughtTokens: __t.f64(),
  costUsd: __t.f64(),
});
export type LlmUsage = __Infer<typeof LlmUsage>;

export const LlmUsageInput = __t.object("LlmUsageInput", {
  route: __t.string(),
  model: __t.string(),
  calls: __t.u32(),
  tokensIn: __t.f64(),
  tokensOut: __t.f64(),
  cachedTokens: __t.f64(),
  thoughtTokens: __t.f64(),
  costUsd: __t.f64(),
});
export type LlmUsageInput = __Infer<typeof LlmUsageInput>;

export const Market = __t.object("Market", {
  conditionId: __t.string(),
  marketId: __t.string(),
  question: __t.string(),
  slug: __t.string(),
  description: __t.string(),
  category: __t.string(),
  endDate: __t.string(),
  yesTokenId: __t.string(),
  noTokenId: __t.string(),
  tickSize: __t.f64(),
  minOrderSize: __t.f64(),
  negRisk: __t.bool(),
  eventId: __t.string(),
  negRiskMarketId: __t.string(),
  outcomeLabel: __t.string(),
  feeRate: __t.f64(),
  active: __t.bool(),
  closed: __t.bool(),
  resolved: __t.bool(),
  outcomeYes: __t.option(__t.f64()),
  bestBid: __t.f64(),
  bestAsk: __t.f64(),
  lastPrice: __t.f64(),
  volumeDay: __t.f64(),
  liquidity: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type Market = __Infer<typeof Market>;

export const MarketInput = __t.object("MarketInput", {
  conditionId: __t.string(),
  marketId: __t.string(),
  question: __t.string(),
  slug: __t.string(),
  description: __t.string(),
  category: __t.string(),
  endDate: __t.string(),
  yesTokenId: __t.string(),
  noTokenId: __t.string(),
  tickSize: __t.f64(),
  minOrderSize: __t.f64(),
  negRisk: __t.bool(),
  eventId: __t.string(),
  negRiskMarketId: __t.string(),
  outcomeLabel: __t.string(),
  feeRate: __t.f64(),
  active: __t.bool(),
  closed: __t.bool(),
  bestBid: __t.f64(),
  bestAsk: __t.f64(),
  lastPrice: __t.f64(),
  volumeDay: __t.f64(),
  liquidity: __t.f64(),
});
export type MarketInput = __Infer<typeof MarketInput>;

export const MemEdge = __t.object("MemEdge", {
  id: __t.u64(),
  key: __t.string(),
  src: __t.u64(),
  dst: __t.u64(),
  rel: __t.string(),
  weight: __t.f64(),
  value: __t.f64(),
  lagMin: __t.f64(),
  evidence: __t.string(),
  sessionId: __t.u64(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  validFrom: __t.timestamp(),
  invalidatedAt: __t.option(__t.timestamp()),
});
export type MemEdge = __Infer<typeof MemEdge>;

export const MemEdgeInput = __t.object("MemEdgeInput", {
  key: __t.string(),
  srcKey: __t.string(),
  dstKey: __t.string(),
  rel: __t.string(),
  weight: __t.f64(),
  value: __t.f64(),
  lagMin: __t.f64(),
  evidence: __t.string(),
  sessionId: __t.u64(),
  status: __t.string(),
});
export type MemEdgeInput = __Infer<typeof MemEdgeInput>;

export const MemNode = __t.object("MemNode", {
  id: __t.u64(),
  key: __t.string(),
  kind: __t.string(),
  label: __t.string(),
  aliases: __t.array(__t.string()),
  summary: __t.string(),
  sessionId: __t.u64(),
  status: __t.string(),
  salience: __t.f64(),
  mentionCount: __t.u32(),
  helpful: __t.u32(),
  harmful: __t.u32(),
  embedding: __t.array(__t.f32()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type MemNode = __Infer<typeof MemNode>;

export const MemNodeInput = __t.object("MemNodeInput", {
  key: __t.string(),
  kind: __t.string(),
  label: __t.string(),
  aliases: __t.array(__t.string()),
  summary: __t.string(),
  sessionId: __t.u64(),
  status: __t.string(),
  salienceDelta: __t.f64(),
  helpfulDelta: __t.u32(),
  harmfulDelta: __t.u32(),
  embedding: __t.array(__t.f32()),
});
export type MemNodeInput = __Infer<typeof MemNodeInput>;

export const NewsInput = __t.object("NewsInput", {
  hash: __t.string(),
  source: __t.string(),
  feed: __t.string(),
  title: __t.string(),
  summary: __t.string(),
  url: __t.string(),
  publishedAt: __t.timestamp(),
  urgency: __t.f64(),
});
export type NewsInput = __Infer<typeof NewsInput>;

export const NewsItem = __t.object("NewsItem", {
  id: __t.u64(),
  hash: __t.string(),
  source: __t.string(),
  feed: __t.string(),
  title: __t.string(),
  summary: __t.string(),
  url: __t.string(),
  publishedAt: __t.timestamp(),
  ingestedAt: __t.timestamp(),
  status: __t.string(),
  urgency: __t.f64(),
  sentiment: __t.f64(),
  novelty: __t.f64(),
  eventType: __t.string(),
  entities: __t.array(__t.string()),
  marketIds: __t.array(__t.string()),
  triageNote: __t.string(),
});
export type NewsItem = __Infer<typeof NewsItem>;

export const NewsTriageInput = __t.object("NewsTriageInput", {
  newsId: __t.u64(),
  status: __t.string(),
  urgency: __t.f64(),
  sentiment: __t.f64(),
  novelty: __t.f64(),
  eventType: __t.string(),
  entities: __t.array(__t.string()),
  marketIds: __t.array(__t.string()),
  triageNote: __t.string(),
});
export type NewsTriageInput = __Infer<typeof NewsTriageInput>;

export const Operator = __t.object("Operator", {
  identity: __t.identity(),
  role: __t.string(),
  createdAt: __t.timestamp(),
});
export type Operator = __Infer<typeof Operator>;

export const OperatorRequest = __t.object("OperatorRequest", {
  id: __t.u64(),
  identity: __t.identity(),
  role: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type OperatorRequest = __Infer<typeof OperatorRequest>;

export const OrderInput = __t.object("OrderInput", {
  ref: __t.string(),
  sessionId: __t.u64(),
  decisionRef: __t.string(),
  conditionId: __t.string(),
  tokenId: __t.string(),
  outcome: __t.string(),
  side: __t.string(),
  price: __t.f64(),
  size: __t.f64(),
  status: __t.string(),
  mode: __t.string(),
  externalId: __t.string(),
  filledSize: __t.f64(),
  avgFillPrice: __t.f64(),
  feeUsd: __t.f64(),
  note: __t.string(),
});
export type OrderInput = __Infer<typeof OrderInput>;

export const PathForecast = __t.object("PathForecast", {
  id: __t.u64(),
  conditionId: __t.string(),
  createdAt: __t.timestamp(),
  baseTs: __t.timestamp(),
  stepSec: __t.u32(),
  lastPrice: __t.f64(),
  point: __t.array(__t.f64()),
  q10: __t.array(__t.f64()),
  q90: __t.array(__t.f64()),
  model: __t.string(),
  newsAdjusted: __t.bool(),
});
export type PathForecast = __Infer<typeof PathForecast>;

export const PathForecastInput = __t.object("PathForecastInput", {
  conditionId: __t.string(),
  baseTs: __t.timestamp(),
  stepSec: __t.u32(),
  lastPrice: __t.f64(),
  point: __t.array(__t.f64()),
  q10: __t.array(__t.f64()),
  q90: __t.array(__t.f64()),
  model: __t.string(),
  newsAdjusted: __t.bool(),
});
export type PathForecastInput = __Infer<typeof PathForecastInput>;

export const Position = __t.object("Position", {
  id: __t.u64(),
  sessionId: __t.u64(),
  conditionId: __t.string(),
  outcome: __t.string(),
  shares: __t.f64(),
  avgPrice: __t.f64(),
  costUsd: __t.f64(),
  markPrice: __t.f64(),
  unrealizedPnlUsd: __t.f64(),
  realizedPnlUsd: __t.f64(),
  closed: __t.bool(),
  strategy: __t.string(),
  targetPrice: __t.f64(),
  stopPrice: __t.f64(),
  timeStopMicros: __t.i64(),
  openedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Position = __Infer<typeof Position>;

export const PositionMarkInput = __t.object("PositionMarkInput", {
  positionId: __t.u64(),
  markPrice: __t.f64(),
});
export type PositionMarkInput = __Infer<typeof PositionMarkInput>;

export const PriceBar = __t.object("PriceBar", {
  id: __t.u64(),
  conditionId: __t.string(),
  ts: __t.timestamp(),
  open: __t.f64(),
  high: __t.f64(),
  low: __t.f64(),
  close: __t.f64(),
  bid: __t.f64(),
  ask: __t.f64(),
});
export type PriceBar = __Infer<typeof PriceBar>;

export const PriceBarInput = __t.object("PriceBarInput", {
  conditionId: __t.string(),
  ts: __t.timestamp(),
  open: __t.f64(),
  high: __t.f64(),
  low: __t.f64(),
  close: __t.f64(),
  bid: __t.f64(),
  ask: __t.f64(),
});
export type PriceBarInput = __Infer<typeof PriceBarInput>;

export const Reflex = __t.object("Reflex", {
  key: __t.string(),
  qtype: __t.string(),
  instructions: __t.string(),
  criteriaKeys: __t.array(__t.string()),
  criteriaText: __t.array(__t.string()),
  threshold: __t.f64(),
  provider: __t.string(),
  version: __t.u32(),
  candidateInstructions: __t.string(),
  candidateThreshold: __t.f64(),
  nFired: __t.u32(),
  nResolved: __t.u32(),
  brier: __t.f64(),
  hitRate: __t.f64(),
  avgLatencyMs: __t.f64(),
  enabled: __t.bool(),
  coachNote: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Reflex = __Infer<typeof Reflex>;

export const ReflexInput = __t.object("ReflexInput", {
  key: __t.string(),
  qtype: __t.string(),
  instructions: __t.string(),
  criteriaKeys: __t.array(__t.string()),
  criteriaText: __t.array(__t.string()),
  threshold: __t.f64(),
  provider: __t.string(),
  version: __t.u32(),
  candidateInstructions: __t.string(),
  candidateThreshold: __t.f64(),
  enabled: __t.bool(),
  coachNote: __t.string(),
});
export type ReflexInput = __Infer<typeof ReflexInput>;

export const ReflexStatsInput = __t.object("ReflexStatsInput", {
  key: __t.string(),
  firedDelta: __t.u32(),
  nResolved: __t.u32(),
  brier: __t.f64(),
  hitRate: __t.f64(),
  avgLatencyMs: __t.f64(),
});
export type ReflexStatsInput = __Infer<typeof ReflexStatsInput>;

export const RiskConfig = __t.object("RiskConfig", {
  kellyFraction: __t.f64(),
  maxPositionPct: __t.f64(),
  maxGrossExposurePct: __t.f64(),
  maxDailyLossPct: __t.f64(),
  maxDrawdownPct: __t.f64(),
  minEdge: __t.f64(),
  maxSpread: __t.f64(),
  modelTrust: __t.f64(),
  maxOpenPositions: __t.u32(),
  strategy: __t.string(),
});
export type RiskConfig = __Infer<typeof RiskConfig>;

export const SeedFile = __t.object("SeedFile", {
  id: __t.u64(),
  sessionId: __t.u64(),
  path: __t.string(),
  kind: __t.string(),
  content: __t.string(),
  version: __t.u32(),
  updatedBy: __t.string(),
  updatedAt: __t.timestamp(),
});
export type SeedFile = __Infer<typeof SeedFile>;

export const SeedFileInput = __t.object("SeedFileInput", {
  path: __t.string(),
  kind: __t.string(),
  content: __t.string(),
});
export type SeedFileInput = __Infer<typeof SeedFileInput>;

export const Session = __t.object("Session", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  slug: __t.string(),
  status: __t.string(),
  statusReason: __t.string(),
  mode: __t.string(),
  liveApproved: __t.bool(),
  bankrollUsd: __t.f64(),
  cashUsd: __t.f64(),
  equityUsd: __t.f64(),
  peakEquityUsd: __t.f64(),
  dayStartEquityUsd: __t.f64(),
  realizedPnlUsd: __t.f64(),
  feesPaidUsd: __t.f64(),
  exposureUsd: __t.f64(),
  get risk() {
    return RiskConfig;
  },
  get intel() {
    return IntelConfig;
  },
  thesis: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Session = __Infer<typeof Session>;

export const SessionMarkInput = __t.object("SessionMarkInput", {
  sessionId: __t.u64(),
  get marks() {
    return __t.array(PositionMarkInput);
  },
  resetDayStart: __t.bool(),
});
export type SessionMarkInput = __Infer<typeof SessionMarkInput>;

export const SessionMarket = __t.object("SessionMarket", {
  id: __t.u64(),
  sessionId: __t.u64(),
  conditionId: __t.string(),
  note: __t.string(),
  prior: __t.option(__t.f64()),
  addedAt: __t.timestamp(),
});
export type SessionMarket = __Infer<typeof SessionMarket>;

export const SessionMarketInput = __t.object("SessionMarketInput", {
  conditionId: __t.string(),
  note: __t.string(),
  prior: __t.option(__t.f64()),
});
export type SessionMarketInput = __Infer<typeof SessionMarketInput>;

export const Signal = __t.object("Signal", {
  id: __t.u64(),
  ref: __t.string(),
  newsId: __t.u64(),
  conditionId: __t.string(),
  createdAt: __t.timestamp(),
  layer: __t.string(),
  expectedDelta: __t.f64(),
  deltaQ10: __t.f64(),
  deltaQ90: __t.f64(),
  halfLifeMin: __t.f64(),
  probYes: __t.f64(),
  probMarket: __t.f64(),
  confidence: __t.f64(),
  disagreement: __t.f64(),
  nAgents: __t.u32(),
  rationale: __t.string(),
  analogCount: __t.u32(),
  analogMeanDelta: __t.f64(),
  realizedShort: __t.option(__t.f64()),
  realizedMid: __t.option(__t.f64()),
  realizedLong: __t.option(__t.f64()),
  absError: __t.option(__t.f64()),
  status: __t.string(),
});
export type Signal = __Infer<typeof Signal>;

export const SignalInput = __t.object("SignalInput", {
  ref: __t.string(),
  newsId: __t.u64(),
  conditionId: __t.string(),
  layer: __t.string(),
  expectedDelta: __t.f64(),
  deltaQ10: __t.f64(),
  deltaQ90: __t.f64(),
  halfLifeMin: __t.f64(),
  probYes: __t.f64(),
  probMarket: __t.f64(),
  confidence: __t.f64(),
  disagreement: __t.f64(),
  nAgents: __t.u32(),
  rationale: __t.string(),
  analogCount: __t.u32(),
  analogMeanDelta: __t.f64(),
});
export type SignalInput = __Infer<typeof SignalInput>;

export const SignalScoreInput = __t.object("SignalScoreInput", {
  signalId: __t.u64(),
  realizedShort: __t.option(__t.f64()),
  realizedMid: __t.option(__t.f64()),
  realizedLong: __t.option(__t.f64()),
  absError: __t.option(__t.f64()),
  final: __t.bool(),
});
export type SignalScoreInput = __Infer<typeof SignalScoreInput>;

export const TaskInput = __t.object("TaskInput", {
  kind: __t.string(),
  sessionId: __t.u64(),
  priority: __t.i32(),
  dependsOn: __t.array(__t.string()),
  dedupeKey: __t.string(),
  payload: __t.string(),
  maxAttempts: __t.u32(),
  notBeforeMicros: __t.i64(),
});
export type TaskInput = __Infer<typeof TaskInput>;

export const TaskUsageInput = __t.object("TaskUsageInput", {
  model: __t.string(),
  tokensIn: __t.u32(),
  tokensOut: __t.u32(),
  cachedTokens: __t.u32(),
  costUsd: __t.f64(),
});
export type TaskUsageInput = __Infer<typeof TaskUsageInput>;

export const TradeOrder = __t.object("TradeOrder", {
  id: __t.u64(),
  ref: __t.string(),
  sessionId: __t.u64(),
  decisionRef: __t.string(),
  conditionId: __t.string(),
  tokenId: __t.string(),
  outcome: __t.string(),
  side: __t.string(),
  price: __t.f64(),
  size: __t.f64(),
  status: __t.string(),
  mode: __t.string(),
  externalId: __t.string(),
  filledSize: __t.f64(),
  avgFillPrice: __t.f64(),
  feeUsd: __t.f64(),
  note: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type TradeOrder = __Infer<typeof TradeOrder>;

export const TrialInput = __t.object("TrialInput", {
  subject: __t.string(),
  agentId: __t.u64(),
  parentId: __t.u64(),
  generation: __t.u32(),
  baselineScore: __t.f64(),
  candidateScore: __t.f64(),
  nEval: __t.u32(),
  decision: __t.string(),
  mutation: __t.string(),
  metric: __t.string(),
});
export type TrialInput = __Infer<typeof TrialInput>;

